using System;
using System.Windows.Forms;
using Apteka.Utils;
using DevExpress.XtraBars;
using Kadr.Database.Views;
using Kadr.GlobalVars;
using Kadr.Models;
using Kadr.Models.Core;

namespace Kadr.Shtat
{
    public partial class frmShtatList : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        private IUnitOfWork db;

        public frmShtatList()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard

            db = new UnitOfWork();

            cbOblastgr.DataSource = DicoDB.dt_SA_OBLAST;
            cbRayongr.DataSource = DicoDB.dt_SA_RAYON_All;
            cbDoljnostgr.DataSource = DicoDB.dt_SA_DOLJNOST;
            cbUcherejgr.DataSource = DicoDB.dt_SA_KOLLEJ;
            cbFangr.DataSource = DicoDB.dt_SA_PREDMET;
            cbKolej.DataSource = DicoDB.dt_SA_KOLLEJ;
            cbOblast.DataSource = DicoDB.dt_SA_OBLAST;
        }

        private void btnClose_ItemClick(object sender, ItemClickEventArgs e)
        {
            Close();
        }

        private void btnNew_ItemClick(object sender, ItemClickEventArgs e)
        {
            var ts = new tbShat();
            ts.Kolej= Vars.Ucherejdeniya;
            ts.Oblast = Vars.Oblast;
            ts.Rayon = Vars.Rayon;
            ts.Doljnost = -1;
            ts.Editdate = DateTime.Today;
            ts.KolChas = 0;
            ts.Predmet = -1;
            ts.State = -1;

            using (frmShtat f = new frmShtat())
            {
                f.bsMain.DataSource = ts;
                if (f.ShowDialog() == DialogResult.OK)
                {
                    var shat  = f.bsMain.Current as tbShat;
                    db.Shat.Add(shat);
                    db.Complete();
                }
            }
        }

        private void btnDel_ItemClick(object sender, ItemClickEventArgs e)
        {
            var r = gridView1.GetFocusedRow() as tbShat;
            if (r != null)
            {
                db.Shat.Remove(r);
                db.Complete();
            }
        }
        private void btnEdit_ItemClick(object sender, ItemClickEventArgs e)
        {
            var r = gridView1.GetFocusedRow() as tbShat;
            if (r != null)
            {
                using (frmShtat f = new frmShtat())
                {
                    f.bsMain.DataSource = r;
                    if (f.ShowDialog() == DialogResult.OK)
                    {
                        var shat = f.bsMain.Current as tbShat;
                        db.Shat.Update(shat);
                        db.Complete();
                    }
                }
            }
        }

        private void cbOblastbe_EditValueChanged(object sender, EventArgs e)
        {
            cbRayon.DataSource = DicoDB.SelectSQL(
               string.Format("SELECT ID, NAME{0} NAME FROM {1} WHERE Obl = {2} ORDER BY NAME",
                   Vars.Lang, "SA_RAYON", cbOblastbe.EditValue));

            cbKolej.DataSource = DicoDB.SelectSQL("select ID, NAME" + Vars.Lang +
                " as NAME from  SA_KOLLEJ WHERE OBL =" + cbRayonbe.EditValue.ToStr());
        }


        private void cbKolejbe_EditValueChanged(object sender, EventArgs e)
        {
            cbKolej.DataSource = DicoDB.SelectSQL("select ID, NAME" + Vars.Lang +
               " as NAME from  SA_KOLLEJ WHERE id =" + cbKolejbe.EditValue.ToStr());
        }
    }
}