//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asbt.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SA_ATESTACIYA_RES> SA_ATESTACIYA_RES { get; set; }
        public virtual DbSet<SA_ATESTACIYA_YN> SA_ATESTACIYA_YN { get; set; }
        public virtual DbSet<SA_CITIZEN> SA_CITIZEN { get; set; }
        public virtual DbSet<SA_COUNTRY> SA_COUNTRY { get; set; }
        public virtual DbSet<SA_DOLJNOST> SA_DOLJNOST { get; set; }
        public virtual DbSet<SA_LANGS> SA_LANGS { get; set; }
        public virtual DbSet<SA_MARRIED> SA_MARRIED { get; set; }
        public virtual DbSet<SA_NAGRADA> SA_NAGRADA { get; set; }
        public virtual DbSet<SA_NAT> SA_NAT { get; set; }
        public virtual DbSet<SA_NAUCHNIY_STEPEN> SA_NAUCHNIY_STEPEN { get; set; }
        public virtual DbSet<SA_OBJLANG> SA_OBJLANG { get; set; }
        public virtual DbSet<SA_OBLAST> SA_OBLAST { get; set; }
        public virtual DbSet<SA_OBRAZOVANIYA> SA_OBRAZOVANIYA { get; set; }
        public virtual DbSet<SA_PARTIYA> SA_PARTIYA { get; set; }
        public virtual DbSet<SA_PEDAGOG_YN> SA_PEDAGOG_YN { get; set; }
        public virtual DbSet<SA_PO_SHATATU> SA_PO_SHATATU { get; set; }
        public virtual DbSet<SA_PROHODIL_YN> SA_PROHODIL_YN { get; set; }
        public virtual DbSet<SA_RABOTAET_YN> SA_RABOTAET_YN { get; set; }
        public virtual DbSet<SA_RAYON> SA_RAYON { get; set; }
        public virtual DbSet<SA_RODSTVENNIK> SA_RODSTVENNIK { get; set; }
        public virtual DbSet<SA_SCSTATUS> SA_SCSTATUS { get; set; }
        public virtual DbSet<SA_SEX> SA_SEX { get; set; }
        public virtual DbSet<SA_SPECIALIST_YN> SA_SPECIALIST_YN { get; set; }
        public virtual DbSet<SA_SPECIALITY> SA_SPECIALITY { get; set; }
        public virtual DbSet<SA_UCHENIY_STEPEN> SA_UCHENIY_STEPEN { get; set; }
        public virtual DbSet<SA_VID_OBUCHENIYA> SA_VID_OBUCHENIYA { get; set; }
        public virtual DbSet<SA_VID_UCHEREJDENI> SA_VID_UCHEREJDENI { get; set; }
        public virtual DbSet<SA_VUZ> SA_VUZ { get; set; }
        public virtual DbSet<SA_YESNO> SA_YESNO { get; set; }
        public virtual DbSet<SCUSER> SCUSERS { get; set; }
        public virtual DbSet<TBATESTATIYA> TBATESTATIYAs { get; set; }
        public virtual DbSet<TBDEPUTY> TBDEPUTies { get; set; }
        public virtual DbSet<TBFOTO> TBFOTOes { get; set; }
        public virtual DbSet<TBGOSNAGRADI> TBGOSNAGRADIs { get; set; }
        public virtual DbSet<TBMAIN> TBMAINs { get; set; }
        public virtual DbSet<TBMESTORAB> TBMESTORABs { get; set; }
        public virtual DbSet<TBPOVISHKVAL> TBPOVISHKVALs { get; set; }
        public virtual DbSet<TBQARINDOSH> TBQARINDOSHes { get; set; }
        public virtual DbSet<TBSHAT> TBSHATs { get; set; }
        public virtual DbSet<TBUNIVER> TBUNIVERs { get; set; }
        public virtual DbSet<DBOPERATOR> DBOPERATORs { get; set; }
    }
}
