//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asbt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_VUZ
    {
        public int ID { get; set; }
        public string NAMEUZ { get; set; }
        public string NAMERU { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public Nullable<int> STATE { get; set; }
    }
}
