//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asbt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCUSER
    {
        public int USERID { get; set; }
        public string LOGINNAME { get; set; }
        public string FULLNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<System.DateTime> LASTACCESS { get; set; }
        public Nullable<int> ENABLED { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> LASTACCTIME { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public Nullable<int> ACCESSCOUNT { get; set; }
        public string LANG { get; set; }
        public string ACSESS { get; set; }
    }
}
