//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asbt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPOVISHKVAL
    {
        public int ID { get; set; }
        public string MAINID { get; set; }
        public Nullable<System.DateTime> DATE_PK { get; set; }
        public Nullable<int> MESTO_PK { get; set; }
        public Nullable<int> POSLEDNIY_PK { get; set; }
        public Nullable<int> NUM_SERTIFICAT { get; set; }
        public Nullable<int> SROK_PALN_PK { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> EDITUSER { get; set; }
    
        public virtual TBMAIN TBMAIN { get; set; }
    }
}
