//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asbt.DataModelsKEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SA_ATESTACIYA_RES> SA_ATESTACIYA_RES { get; set; }
        public DbSet<SA_ATESTACIYA_YN> SA_ATESTACIYA_YN { get; set; }
        public DbSet<SA_COUNTRY> SA_COUNTRY { get; set; }
        public DbSet<SA_DOLJNOST> SA_DOLJNOST { get; set; }
        public DbSet<SA_HARBIY_UNVON> SA_HARBIY_UNVON { get; set; }
        public DbSet<SA_KOLLEJ> SA_KOLLEJ { get; set; }
        public DbSet<SA_LANGS> SA_LANGS { get; set; }
        public DbSet<SA_MARRIED> SA_MARRIED { get; set; }
        public DbSet<SA_MASTER_KATEGORIYA> SA_MASTER_KATEGORIYA { get; set; }
        public DbSet<SA_NAGRADA> SA_NAGRADA { get; set; }
        public DbSet<SA_NAT> SA_NAT { get; set; }
        public DbSet<SA_OBJLANG> SA_OBJLANG { get; set; }
        public DbSet<SA_OBLAST> SA_OBLAST { get; set; }
        public DbSet<SA_OBRAZOVANIYA> SA_OBRAZOVANIYA { get; set; }
        public DbSet<SA_PARTIYA> SA_PARTIYA { get; set; }
        public DbSet<SA_PEDAGOG_YN> SA_PEDAGOG_YN { get; set; }
        public DbSet<SA_PEDOBRAZOVANIE> SA_PEDOBRAZOVANIE { get; set; }
        public DbSet<SA_PEDPEREPOD> SA_PEDPEREPOD { get; set; }
        public DbSet<SA_PINYAT_NA_RABOTU> SA_PINYAT_NA_RABOTU { get; set; }
        public DbSet<SA_PO_SHATATU> SA_PO_SHATATU { get; set; }
        public DbSet<SA_PREDMET> SA_PREDMET { get; set; }
        public DbSet<SA_PROHODIL_YN> SA_PROHODIL_YN { get; set; }
        public DbSet<SA_RABOTAET_YN> SA_RABOTAET_YN { get; set; }
        public DbSet<SA_RAYON> SA_RAYON { get; set; }
        public DbSet<SA_RODSTVENNIK> SA_RODSTVENNIK { get; set; }
        public DbSet<SA_SCSTATUS> SA_SCSTATUS { get; set; }
        public DbSet<SA_SEX> SA_SEX { get; set; }
        public DbSet<SA_SPECIALIST_YN> SA_SPECIALIST_YN { get; set; }
        public DbSet<SA_SPECIALITY> SA_SPECIALITY { get; set; }
        public DbSet<SA_UCHENIY_STEPEN> SA_UCHENIY_STEPEN { get; set; }
        public DbSet<SA_VID_OBUCHENIYA> SA_VID_OBUCHENIYA { get; set; }
        public DbSet<SA_VID_PREDMETA> SA_VID_PREDMETA { get; set; }
        public DbSet<SA_VID_UCHEREJDENI> SA_VID_UCHEREJDENI { get; set; }
        public DbSet<SA_VID_UCHEREJDENI_DIPLOM> SA_VID_UCHEREJDENI_DIPLOM { get; set; }
        public DbSet<SA_VUZ> SA_VUZ { get; set; }
        public DbSet<SA_YESNO> SA_YESNO { get; set; }
        public DbSet<SCUSER> SCUSERS { get; set; }
        public DbSet<TBATESTATIYA> TBATESTATIYAs { get; set; }
        public DbSet<TBDEPUTY> TBDEPUTies { get; set; }
        public DbSet<TBFOTO> TBFOTOes { get; set; }
        public DbSet<TBGOSNAGRADI> TBGOSNAGRADIs { get; set; }
        public DbSet<TBMAIN> TBMAINs { get; set; }
        public DbSet<TBMESTORAB> TBMESTORABs { get; set; }
        public DbSet<TBPOVISHKVAL> TBPOVISHKVALs { get; set; }
        public DbSet<TBQARINDOSH> TBQARINDOSHes { get; set; }
        public DbSet<TBSHAT> TBSHATs { get; set; }
        public DbSet<TBUNIVER> TBUNIVERs { get; set; }
        public DbSet<DBOPERATOR> DBOPERATORs { get; set; }
    
        [EdmFunction("Entities", "TBATESTATIYA_SEL")]
        public virtual IQueryable<TBATESTATIYA_SEL_Result> TBATESTATIYA_SEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TBATESTATIYA_SEL_Result>("[Entities].[TBATESTATIYA_SEL]()");
        }
    
        [EdmFunction("Entities", "TBDEPUTY_SEL")]
        public virtual IQueryable<TBDEPUTY_SEL_Result> TBDEPUTY_SEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TBDEPUTY_SEL_Result>("[Entities].[TBDEPUTY_SEL]()");
        }
    
        [EdmFunction("Entities", "TBGOSNAGRADI_SEL")]
        public virtual IQueryable<TBGOSNAGRADI_SEL_Result> TBGOSNAGRADI_SEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TBGOSNAGRADI_SEL_Result>("[Entities].[TBGOSNAGRADI_SEL]()");
        }
    
        [EdmFunction("Entities", "TBMAIN_SEL")]
        public virtual IQueryable<TBMAIN_SEL_Result> TBMAIN_SEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TBMAIN_SEL_Result>("[Entities].[TBMAIN_SEL]()");
        }
    
        [EdmFunction("Entities", "TBMESTORAB_SEL")]
        public virtual IQueryable<TBMESTORAB_SEL_Result> TBMESTORAB_SEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TBMESTORAB_SEL_Result>("[Entities].[TBMESTORAB_SEL]()");
        }
    
        [EdmFunction("Entities", "TBPOVISHKVAL_SEL")]
        public virtual IQueryable<TBPOVISHKVAL_SEL_Result> TBPOVISHKVAL_SEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TBPOVISHKVAL_SEL_Result>("[Entities].[TBPOVISHKVAL_SEL]()");
        }
    
        [EdmFunction("Entities", "TBQARINDOSH_SEL")]
        public virtual IQueryable<TBQARINDOSH_SEL_Result> TBQARINDOSH_SEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TBQARINDOSH_SEL_Result>("[Entities].[TBQARINDOSH_SEL]()");
        }
    
        [EdmFunction("Entities", "TBSHAT_SEL")]
        public virtual IQueryable<TBSHAT_SEL_Result> TBSHAT_SEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TBSHAT_SEL_Result>("[Entities].[TBSHAT_SEL]()");
        }
    
        [EdmFunction("Entities", "TBUNIVER_SEL")]
        public virtual IQueryable<TBUNIVER_SEL_Result> TBUNIVER_SEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TBUNIVER_SEL_Result>("[Entities].[TBUNIVER_SEL]()");
        }
    }
}
