//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asbt.DataModelsKEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_MARRIED
    {
        public int ID { get; set; }
        public string NAMEUZ { get; set; }
        public string NAMERU { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public Nullable<int> STATE { get; set; }
    }
}
