//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asbt.DataModelsKEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCUSER
    {
        public int USERID { get; set; }
        public string LOGINNAME { get; set; }
        public string FULLNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<System.DateTime> LASTACCESS { get; set; }
        public Nullable<int> ENABLED { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> LASTACCTIME { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public Nullable<int> ACCESSCOUNT { get; set; }
        public string LANG { get; set; }
        public string ACSESS { get; set; }
    }
}
