//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asbt.DataModelsKEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBATESTATIYA
    {
        public int ID { get; set; }
        public string MAINID { get; set; }
        public Nullable<int> PRIVLICHEN_YN { get; set; }
        public Nullable<System.DateTime> DATE_AT { get; set; }
        public Nullable<int> RESULT_AA { get; set; }
        public Nullable<int> DOLJNOST_POSLE { get; set; }
        public string PICHINA_NE_PRIVLICHENIYA { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> EDITUSER { get; set; }
        public string PICHINA_NE_PRIVLICHENIYA_RU { get; set; }
    }
}
