//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asbt.DataModelsKEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPOVISHKVAL
    {
        public int ID { get; set; }
        public string MAINID { get; set; }
        public Nullable<System.DateTime> DATE_PK { get; set; }
        public Nullable<int> MESTO_PK { get; set; }
        public Nullable<int> POSLEDNIY_PK { get; set; }
        public string NUM_SERTIFICAT { get; set; }
        public Nullable<int> SROK_PALN_PK { get; set; }
        public Nullable<int> PEDOBRAZOVANIEPK { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> EDITUSER { get; set; }
    }
}
