//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asbt.DataModelsKEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSHAT
    {
        public int ID { get; set; }
        public Nullable<int> OBLAST { get; set; }
        public Nullable<int> RAYON { get; set; }
        public Nullable<int> KOLEJ { get; set; }
        public Nullable<decimal> KOL_CHAS { get; set; }
        public Nullable<int> DOLJNOST { get; set; }
        public Nullable<int> PREDMET { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> STATE { get; set; }
    }
}
