//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asbt.DataModelsKEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUNIVER
    {
        public int ID { get; set; }
        public string MAINID { get; set; }
        public string GOD_VIPUSKA { get; set; }
        public Nullable<int> OBRAZOVATELNIY_UCHERJ { get; set; }
        public string SPECIALNOST_PODIPLOMU { get; set; }
        public Nullable<int> VID_OBUCHENIYA { get; set; }
        public Nullable<int> PROFESIANAL_OBRAZ { get; set; }
        public Nullable<int> OB_TYPE { get; set; }
        public string SERIYA { get; set; }
        public Nullable<int> NUM { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> EDITUSER { get; set; }
        public string SPECIALNOST_PODIPLOMU_RU { get; set; }
    }
}
