//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Asbt.Data.Xpo
{

    public partial class SCUSERS : XPLiteObject
    {
        string fACSESS;
        [Size(1000)]
        public string ACSESS
        {
            get { return fACSESS; }
            set { SetPropertyValue<string>("ACSESS", ref fACSESS, value); }
        }
        int fUSERID;
        [Key]
        public int USERID
        {
            get { return fUSERID; }
            set { SetPropertyValue<int>("USERID", ref fUSERID, value); }
        }
        string fLOGINNAME;
        [Size(50)]
        public string LOGINNAME
        {
            get { return fLOGINNAME; }
            set { SetPropertyValue<string>("LOGINNAME", ref fLOGINNAME, value); }
        }
        string fFULLNAME;
        [Size(50)]
        public string FULLNAME
        {
            get { return fFULLNAME; }
            set { SetPropertyValue<string>("FULLNAME", ref fFULLNAME, value); }
        }
        string fPASSWORD;
        [Size(50)]
        public string PASSWORD
        {
            get { return fPASSWORD; }
            set { SetPropertyValue<string>("PASSWORD", ref fPASSWORD, value); }
        }
        DateTime fLASTACCESS;
        public DateTime LASTACCESS
        {
            get { return fLASTACCESS; }
            set { SetPropertyValue<DateTime>("LASTACCESS", ref fLASTACCESS, value); }
        }
        int fENABLED;
        public int ENABLED
        {
            get { return fENABLED; }
            set { SetPropertyValue<int>("ENABLED", ref fENABLED, value); }
        }
        DateTime fCREATEDDATE;
        public DateTime CREATEDDATE
        {
            get { return fCREATEDDATE; }
            set { SetPropertyValue<DateTime>("CREATEDDATE", ref fCREATEDDATE, value); }
        }
        DateTime fLASTACCTIME;
        public DateTime LASTACCTIME
        {
            get { return fLASTACCTIME; }
            set { SetPropertyValue<DateTime>("LASTACCTIME", ref fLASTACCTIME, value); }
        }
        DateTime fCREATEDTIME;
        public DateTime CREATEDTIME
        {
            get { return fCREATEDTIME; }
            set { SetPropertyValue<DateTime>("CREATEDTIME", ref fCREATEDTIME, value); }
        }
        int fACCESSCOUNT;
        public int ACCESSCOUNT
        {
            get { return fACCESSCOUNT; }
            set { SetPropertyValue<int>("ACCESSCOUNT", ref fACCESSCOUNT, value); }
        }
        string fLANG;
        [Size(2)]
        public string LANG
        {
            get { return fLANG; }
            set { SetPropertyValue<string>("LANG", ref fLANG, value); }
        }
    }

}
