//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Asbt.Data.Xpo
{

    public partial class TBMAIN : XPLiteObject
    {
        int fST_REGION;
        public int ST_REGION
        {
            get { return fST_REGION; }
            set { SetPropertyValue<int>("ST_REGION", ref fST_REGION, value); }
        }
        int fST_RAYON;
        public int ST_RAYON
        {
            get { return fST_RAYON; }
            set { SetPropertyValue<int>("ST_RAYON", ref fST_RAYON, value); }
        }
        string fID;
        [Key]
        [Size(50)]
        public string ID
        {
            get { return fID; }
            set { SetPropertyValue<string>("ID", ref fID, value); }
        }
        string fFIRSTNAME;
        [Size(50)]
        public string FIRSTNAME
        {
            get { return fFIRSTNAME; }
            set { SetPropertyValue<string>("FIRSTNAME", ref fFIRSTNAME, value); }
        }
        string fLASTNAME;
        [Size(50)]
        public string LASTNAME
        {
            get { return fLASTNAME; }
            set { SetPropertyValue<string>("LASTNAME", ref fLASTNAME, value); }
        }
        string fPATRONYMIC;
        [Size(50)]
        public string PATRONYMIC
        {
            get { return fPATRONYMIC; }
            set { SetPropertyValue<string>("PATRONYMIC", ref fPATRONYMIC, value); }
        }
        string fFIO_REL;
        [Size(200)]
        public string FIO_REL
        {
            get { return fFIO_REL; }
            set { SetPropertyValue<string>("FIO_REL", ref fFIO_REL, value); }
        }
        DateTime fBIRTHDATE;
        public DateTime BIRTHDATE
        {
            get { return fBIRTHDATE; }
            set { SetPropertyValue<DateTime>("BIRTHDATE", ref fBIRTHDATE, value); }
        }
        int fBIRTHCOUNTRY;
        public int BIRTHCOUNTRY
        {
            get { return fBIRTHCOUNTRY; }
            set { SetPropertyValue<int>("BIRTHCOUNTRY", ref fBIRTHCOUNTRY, value); }
        }
        int fBIRTHREGION;
        public int BIRTHREGION
        {
            get { return fBIRTHREGION; }
            set { SetPropertyValue<int>("BIRTHREGION", ref fBIRTHREGION, value); }
        }
        int fBIRTHTOWN;
        public int BIRTHTOWN
        {
            get { return fBIRTHTOWN; }
            set { SetPropertyValue<int>("BIRTHTOWN", ref fBIRTHTOWN, value); }
        }
        int fNATIONALITY;
        public int NATIONALITY
        {
            get { return fNATIONALITY; }
            set { SetPropertyValue<int>("NATIONALITY", ref fNATIONALITY, value); }
        }
        int fPOST;
        public int POST
        {
            get { return fPOST; }
            set { SetPropertyValue<int>("POST", ref fPOST, value); }
        }
        int fSEX;
        public int SEX
        {
            get { return fSEX; }
            set { SetPropertyValue<int>("SEX", ref fSEX, value); }
        }
        string fOBJLANG;
        [Size(2)]
        public string OBJLANG
        {
            get { return fOBJLANG; }
            set { SetPropertyValue<string>("OBJLANG", ref fOBJLANG, value); }
        }
        int fMARRIED;
        public int MARRIED
        {
            get { return fMARRIED; }
            set { SetPropertyValue<int>("MARRIED", ref fMARRIED, value); }
        }
        string fLANGS;
        [Size(150)]
        public string LANGS
        {
            get { return fLANGS; }
            set { SetPropertyValue<string>("LANGS", ref fLANGS, value); }
        }
        int fSTATEPRIZES;
        public int STATEPRIZES
        {
            get { return fSTATEPRIZES; }
            set { SetPropertyValue<int>("STATEPRIZES", ref fSTATEPRIZES, value); }
        }
        int fREGION_PROPISKA;
        public int REGION_PROPISKA
        {
            get { return fREGION_PROPISKA; }
            set { SetPropertyValue<int>("REGION_PROPISKA", ref fREGION_PROPISKA, value); }
        }
        int fRAYON_PROPISKA;
        public int RAYON_PROPISKA
        {
            get { return fRAYON_PROPISKA; }
            set { SetPropertyValue<int>("RAYON_PROPISKA", ref fRAYON_PROPISKA, value); }
        }
        string fQISHLOQ_PROPISKA;
        [Size(150)]
        public string QISHLOQ_PROPISKA
        {
            get { return fQISHLOQ_PROPISKA; }
            set { SetPropertyValue<string>("QISHLOQ_PROPISKA", ref fQISHLOQ_PROPISKA, value); }
        }
        string fUY_PROPISKA;
        [Size(150)]
        public string UY_PROPISKA
        {
            get { return fUY_PROPISKA; }
            set { SetPropertyValue<string>("UY_PROPISKA", ref fUY_PROPISKA, value); }
        }
        DateTime fCWORKDATE;
        public DateTime CWORKDATE
        {
            get { return fCWORKDATE; }
            set { SetPropertyValue<DateTime>("CWORKDATE", ref fCWORKDATE, value); }
        }
        DateTime fCWORKLEAVEDATE;
        public DateTime CWORKLEAVEDATE
        {
            get { return fCWORKLEAVEDATE; }
            set { SetPropertyValue<DateTime>("CWORKLEAVEDATE", ref fCWORKLEAVEDATE, value); }
        }
        int fCWORKPLACE;
        public int CWORKPLACE
        {
            get { return fCWORKPLACE; }
            set { SetPropertyValue<int>("CWORKPLACE", ref fCWORKPLACE, value); }
        }
        string fCWORKDEPART;
        [Size(500)]
        public string CWORKDEPART
        {
            get { return fCWORKDEPART; }
            set { SetPropertyValue<string>("CWORKDEPART", ref fCWORKDEPART, value); }
        }
        string fOBJWORKPLACE;
        [Size(1000)]
        public string OBJWORKPLACE
        {
            get { return fOBJWORKPLACE; }
            set { SetPropertyValue<string>("OBJWORKPLACE", ref fOBJWORKPLACE, value); }
        }
        string fWORKPHONE;
        public string WORKPHONE
        {
            get { return fWORKPHONE; }
            set { SetPropertyValue<string>("WORKPHONE", ref fWORKPHONE, value); }
        }
        string fHOMEPHONE;
        [Size(25)]
        public string HOMEPHONE
        {
            get { return fHOMEPHONE; }
            set { SetPropertyValue<string>("HOMEPHONE", ref fHOMEPHONE, value); }
        }
        string fCELLPHONE;
        [Size(25)]
        public string CELLPHONE
        {
            get { return fCELLPHONE; }
            set { SetPropertyValue<string>("CELLPHONE", ref fCELLPHONE, value); }
        }
        string fFAXNUMBER;
        [Size(25)]
        public string FAXNUMBER
        {
            get { return fFAXNUMBER; }
            set { SetPropertyValue<string>("FAXNUMBER", ref fFAXNUMBER, value); }
        }
        string fEMAIL;
        [Size(50)]
        public string EMAIL
        {
            get { return fEMAIL; }
            set { SetPropertyValue<string>("EMAIL", ref fEMAIL, value); }
        }
        string fPASS_SERIES;
        [Size(10)]
        public string PASS_SERIES
        {
            get { return fPASS_SERIES; }
            set { SetPropertyValue<string>("PASS_SERIES", ref fPASS_SERIES, value); }
        }
        string fPASS_NUMBER;
        [Size(20)]
        public string PASS_NUMBER
        {
            get { return fPASS_NUMBER; }
            set { SetPropertyValue<string>("PASS_NUMBER", ref fPASS_NUMBER, value); }
        }
        DateTime fPASS_GIVENDATE;
        public DateTime PASS_GIVENDATE
        {
            get { return fPASS_GIVENDATE; }
            set { SetPropertyValue<DateTime>("PASS_GIVENDATE", ref fPASS_GIVENDATE, value); }
        }
        string fPASS_GIVENBY;
        [Size(150)]
        public string PASS_GIVENBY
        {
            get { return fPASS_GIVENBY; }
            set { SetPropertyValue<string>("PASS_GIVENBY", ref fPASS_GIVENBY, value); }
        }
        int fPARTY;
        public int PARTY
        {
            get { return fPARTY; }
            set { SetPropertyValue<int>("PARTY", ref fPARTY, value); }
        }
        int fEDUCATION;
        public int EDUCATION
        {
            get { return fEDUCATION; }
            set { SetPropertyValue<int>("EDUCATION", ref fEDUCATION, value); }
        }
        int fVUZ;
        public int VUZ
        {
            get { return fVUZ; }
            set { SetPropertyValue<int>("VUZ", ref fVUZ, value); }
        }
        int fSPECIALITY;
        public int SPECIALITY
        {
            get { return fSPECIALITY; }
            set { SetPropertyValue<int>("SPECIALITY", ref fSPECIALITY, value); }
        }
        int fSCSTATUS;
        public int SCSTATUS
        {
            get { return fSCSTATUS; }
            set { SetPropertyValue<int>("SCSTATUS", ref fSCSTATUS, value); }
        }
        string fSCDEGREE;
        [Size(250)]
        public string SCDEGREE
        {
            get { return fSCDEGREE; }
            set { SetPropertyValue<string>("SCDEGREE", ref fSCDEGREE, value); }
        }
        int fSERVICE;
        public int SERVICE
        {
            get { return fSERVICE; }
            set { SetPropertyValue<int>("SERVICE", ref fSERVICE, value); }
        }
        int fZVANIE;
        public int ZVANIE
        {
            get { return fZVANIE; }
            set { SetPropertyValue<int>("ZVANIE", ref fZVANIE, value); }
        }
        string fSUDIMOST_RODST;
        [Size(250)]
        public string SUDIMOST_RODST
        {
            get { return fSUDIMOST_RODST; }
            set { SetPropertyValue<string>("SUDIMOST_RODST", ref fSUDIMOST_RODST, value); }
        }
        string fTAVSIFNOMA;
        [Size(5000)]
        public string TAVSIFNOMA
        {
            get { return fTAVSIFNOMA; }
            set { SetPropertyValue<string>("TAVSIFNOMA", ref fTAVSIFNOMA, value); }
        }
        string fADDITIONAL_INFO;
        [Size(5000)]
        public string ADDITIONAL_INFO
        {
            get { return fADDITIONAL_INFO; }
            set { SetPropertyValue<string>("ADDITIONAL_INFO", ref fADDITIONAL_INFO, value); }
        }
        string fCARDNUM;
        [Size(20)]
        public string CARDNUM
        {
            get { return fCARDNUM; }
            set { SetPropertyValue<string>("CARDNUM", ref fCARDNUM, value); }
        }
        DateTime fEDITDATE;
        public DateTime EDITDATE
        {
            get { return fEDITDATE; }
            set { SetPropertyValue<DateTime>("EDITDATE", ref fEDITDATE, value); }
        }
        DateTime fCREATEDATE;
        public DateTime CREATEDATE
        {
            get { return fCREATEDATE; }
            set { SetPropertyValue<DateTime>("CREATEDATE", ref fCREATEDATE, value); }
        }
        int fEDITUSER;
        public int EDITUSER
        {
            get { return fEDITUSER; }
            set { SetPropertyValue<int>("EDITUSER", ref fEDITUSER, value); }
        }
        int fCREATEUSER;
        public int CREATEUSER
        {
            get { return fCREATEUSER; }
            set { SetPropertyValue<int>("CREATEUSER", ref fCREATEUSER, value); }
        }
        int fACTIVE;
        public int ACTIVE
        {
            get { return fACTIVE; }
            set { SetPropertyValue<int>("ACTIVE", ref fACTIVE, value); }
        }
        int fCARDSTATE;
        public int CARDSTATE
        {
            get { return fCARDSTATE; }
            set { SetPropertyValue<int>("CARDSTATE", ref fCARDSTATE, value); }
        }
        int fCONTRY_PROPISKA;
        public int CONTRY_PROPISKA
        {
            get { return fCONTRY_PROPISKA; }
            set { SetPropertyValue<int>("CONTRY_PROPISKA", ref fCONTRY_PROPISKA, value); }
        }
        string fHONADON_PROPISKA;
        [Size(10)]
        public string HONADON_PROPISKA
        {
            get { return fHONADON_PROPISKA; }
            set { SetPropertyValue<string>("HONADON_PROPISKA", ref fHONADON_PROPISKA, value); }
        }
        string fKUCHA_PROPISKA;
        public string KUCHA_PROPISKA
        {
            get { return fKUCHA_PROPISKA; }
            set { SetPropertyValue<string>("KUCHA_PROPISKA", ref fKUCHA_PROPISKA, value); }
        }
        int fST_VIDUCHEREJDENIYA;
        public int ST_VIDUCHEREJDENIYA
        {
            get { return fST_VIDUCHEREJDENIYA; }
            set { SetPropertyValue<int>("ST_VIDUCHEREJDENIYA", ref fST_VIDUCHEREJDENIYA, value); }
        }
        int fVID_GRAJDANSTVO;
        public int VID_GRAJDANSTVO
        {
            get { return fVID_GRAJDANSTVO; }
            set { SetPropertyValue<int>("VID_GRAJDANSTVO", ref fVID_GRAJDANSTVO, value); }
        }
        int fVOZROST;
        public int VOZROST
        {
            get { return fVOZROST; }
            set { SetPropertyValue<int>("VOZROST", ref fVOZROST, value); }
        }
        int fDETI_KOL;
        public int DETI_KOL
        {
            get { return fDETI_KOL; }
            set { SetPropertyValue<int>("DETI_KOL", ref fDETI_KOL, value); }
        }
        int fVID_DOLJNOST;
        public int VID_DOLJNOST
        {
            get { return fVID_DOLJNOST; }
            set { SetPropertyValue<int>("VID_DOLJNOST", ref fVID_DOLJNOST, value); }
        }
        int fKATEGORIYA_MASTERA;
        public int KATEGORIYA_MASTERA
        {
            get { return fKATEGORIYA_MASTERA; }
            set { SetPropertyValue<int>("KATEGORIYA_MASTERA", ref fKATEGORIYA_MASTERA, value); }
        }
        int fVID_PRIN_NA_RABOTU;
        public int VID_PRIN_NA_RABOTU
        {
            get { return fVID_PRIN_NA_RABOTU; }
            set { SetPropertyValue<int>("VID_PRIN_NA_RABOTU", ref fVID_PRIN_NA_RABOTU, value); }
        }
        string fNUM_PRIKAZA;
        [Size(50)]
        public string NUM_PRIKAZA
        {
            get { return fNUM_PRIKAZA; }
            set { SetPropertyValue<string>("NUM_PRIKAZA", ref fNUM_PRIKAZA, value); }
        }
        DateTime fDATA_PRIKAZA;
        public DateTime DATA_PRIKAZA
        {
            get { return fDATA_PRIKAZA; }
            set { SetPropertyValue<DateTime>("DATA_PRIKAZA", ref fDATA_PRIKAZA, value); }
        }
        int fPO_SHTATU;
        public int PO_SHTATU
        {
            get { return fPO_SHTATU; }
            set { SetPropertyValue<int>("PO_SHTATU", ref fPO_SHTATU, value); }
        }
        int fOBSHIY_STAJ;
        public int OBSHIY_STAJ
        {
            get { return fOBSHIY_STAJ; }
            set { SetPropertyValue<int>("OBSHIY_STAJ", ref fOBSHIY_STAJ, value); }
        }
        int fPED_STAJ;
        public int PED_STAJ
        {
            get { return fPED_STAJ; }
            set { SetPropertyValue<int>("PED_STAJ", ref fPED_STAJ, value); }
        }
        int fDAN_DOLJ_STAJ;
        public int DAN_DOLJ_STAJ
        {
            get { return fDAN_DOLJ_STAJ; }
            set { SetPropertyValue<int>("DAN_DOLJ_STAJ", ref fDAN_DOLJ_STAJ, value); }
        }
        int fVID_PRED_OS_PREDMET;
        public int VID_PRED_OS_PREDMET
        {
            get { return fVID_PRED_OS_PREDMET; }
            set { SetPropertyValue<int>("VID_PRED_OS_PREDMET", ref fVID_PRED_OS_PREDMET, value); }
        }
        int fNAIM_PRED_OS_PREDMET;
        public int NAIM_PRED_OS_PREDMET
        {
            get { return fNAIM_PRED_OS_PREDMET; }
            set { SetPropertyValue<int>("NAIM_PRED_OS_PREDMET", ref fNAIM_PRED_OS_PREDMET, value); }
        }
        int fYAZIK_OS_PREPODAET;
        public int YAZIK_OS_PREPODAET
        {
            get { return fYAZIK_OS_PREPODAET; }
            set { SetPropertyValue<int>("YAZIK_OS_PREPODAET", ref fYAZIK_OS_PREPODAET, value); }
        }
        int fVID_PRED_DP_PREDMET;
        public int VID_PRED_DP_PREDMET
        {
            get { return fVID_PRED_DP_PREDMET; }
            set { SetPropertyValue<int>("VID_PRED_DP_PREDMET", ref fVID_PRED_DP_PREDMET, value); }
        }
        int fNAIM_PRED_DP_PREDMET;
        public int NAIM_PRED_DP_PREDMET
        {
            get { return fNAIM_PRED_DP_PREDMET; }
            set { SetPropertyValue<int>("NAIM_PRED_DP_PREDMET", ref fNAIM_PRED_DP_PREDMET, value); }
        }
        int fYAZIK_DP_PREPODAET;
        public int YAZIK_DP_PREPODAET
        {
            get { return fYAZIK_DP_PREPODAET; }
            set { SetPropertyValue<int>("YAZIK_DP_PREPODAET", ref fYAZIK_DP_PREPODAET, value); }
        }
        int fSPEC_DP_PREDMET;
        public int SPEC_DP_PREDMET
        {
            get { return fSPEC_DP_PREDMET; }
            set { SetPropertyValue<int>("SPEC_DP_PREDMET", ref fSPEC_DP_PREDMET, value); }
        }
        int fVSEGO_KOL_CHASOV;
        public int VSEGO_KOL_CHASOV
        {
            get { return fVSEGO_KOL_CHASOV; }
            set { SetPropertyValue<int>("VSEGO_KOL_CHASOV", ref fVSEGO_KOL_CHASOV, value); }
        }
        int fPED_PEREPOD;
        public int PED_PEREPOD
        {
            get { return fPED_PEREPOD; }
            set { SetPropertyValue<int>("PED_PEREPOD", ref fPED_PEREPOD, value); }
        }
        int fPED_PEREPOD_GDE;
        public int PED_PEREPOD_GDE
        {
            get { return fPED_PEREPOD_GDE; }
            set { SetPropertyValue<int>("PED_PEREPOD_GDE", ref fPED_PEREPOD_GDE, value); }
        }
        DateTime fDATA_PED_PEREPOD;
        public DateTime DATA_PED_PEREPOD
        {
            get { return fDATA_PED_PEREPOD; }
            set { SetPropertyValue<DateTime>("DATA_PED_PEREPOD", ref fDATA_PED_PEREPOD, value); }
        }
        string fNUMDIPLOM_PED_PERE;
        [Size(50)]
        public string NUMDIPLOM_PED_PERE
        {
            get { return fNUMDIPLOM_PED_PERE; }
            set { SetPropertyValue<string>("NUMDIPLOM_PED_PERE", ref fNUMDIPLOM_PED_PERE, value); }
        }
        int fPRIVLECHENIE_ATTECTAC;
        public int PRIVLECHENIE_ATTECTAC
        {
            get { return fPRIVLECHENIE_ATTECTAC; }
            set { SetPropertyValue<int>("PRIVLECHENIE_ATTECTAC", ref fPRIVLECHENIE_ATTECTAC, value); }
        }
        int fDATA_POSLED_ATTECTAC;
        public int DATA_POSLED_ATTECTAC
        {
            get { return fDATA_POSLED_ATTECTAC; }
            set { SetPropertyValue<int>("DATA_POSLED_ATTECTAC", ref fDATA_POSLED_ATTECTAC, value); }
        }
        int fRES_ATTECTAC;
        public int RES_ATTECTAC
        {
            get { return fRES_ATTECTAC; }
            set { SetPropertyValue<int>("RES_ATTECTAC", ref fRES_ATTECTAC, value); }
        }
        int fDOLJNOST_ATTECTAC;
        public int DOLJNOST_ATTECTAC
        {
            get { return fDOLJNOST_ATTECTAC; }
            set { SetPropertyValue<int>("DOLJNOST_ATTECTAC", ref fDOLJNOST_ATTECTAC, value); }
        }
        int fPRICHINI_NE_PRIV_ATTECTAC;
        public int PRICHINI_NE_PRIV_ATTECTAC
        {
            get { return fPRICHINI_NE_PRIV_ATTECTAC; }
            set { SetPropertyValue<int>("PRICHINI_NE_PRIV_ATTECTAC", ref fPRICHINI_NE_PRIV_ATTECTAC, value); }
        }
        int fINOST_YAZIK;
        public int INOST_YAZIK
        {
            get { return fINOST_YAZIK; }
            set { SetPropertyValue<int>("INOST_YAZIK", ref fINOST_YAZIK, value); }
        }
        int fZANYA_KOMPUTERA;
        public int ZANYA_KOMPUTERA
        {
            get { return fZANYA_KOMPUTERA; }
            set { SetPropertyValue<int>("ZANYA_KOMPUTERA", ref fZANYA_KOMPUTERA, value); }
        }
        int fDANNIY_OTCH_PERIODE;
        public int DANNIY_OTCH_PERIODE
        {
            get { return fDANNIY_OTCH_PERIODE; }
            set { SetPropertyValue<int>("DANNIY_OTCH_PERIODE", ref fDANNIY_OTCH_PERIODE, value); }
        }
        int fPRICHINA;
        public int PRICHINA
        {
            get { return fPRICHINA; }
            set { SetPropertyValue<int>("PRICHINA", ref fPRICHINA, value); }
        }
        decimal fSTAVKA_CHAS;
        public decimal STAVKA_CHAS
        {
            get { return fSTAVKA_CHAS; }
            set { SetPropertyValue<decimal>("STAVKA_CHAS", ref fSTAVKA_CHAS, value); }
        }
        int fTOIFA;
        public int TOIFA
        {
            get { return fTOIFA; }
            set { SetPropertyValue<int>("TOIFA", ref fTOIFA, value); }
        }
        int fSPEC_OS_PREDMET;
        public int SPEC_OS_PREDMET
        {
            get { return fSPEC_OS_PREDMET; }
            set { SetPropertyValue<int>("SPEC_OS_PREDMET", ref fSPEC_OS_PREDMET, value); }
        }
        int fPED_OBRAZ;
        public int PED_OBRAZ
        {
            get { return fPED_OBRAZ; }
            set { SetPropertyValue<int>("PED_OBRAZ", ref fPED_OBRAZ, value); }
        }
        [Association(@"TBATESTATIYAReferencesTBMAIN", typeof(TBATESTATIYA))]
        public XPCollection<TBATESTATIYA> TBATESTATIYAs { get { return GetCollection<TBATESTATIYA>("TBATESTATIYAs"); } }
        [Association(@"TBDEPUTYReferencesTBMAIN", typeof(TBDEPUTY))]
        public XPCollection<TBDEPUTY> TBDEPUTies { get { return GetCollection<TBDEPUTY>("TBDEPUTies"); } }
        [Association(@"TBFOTOReferencesTBMAIN", typeof(TBFOTO))]
        public XPCollection<TBFOTO> TBFOTOes { get { return GetCollection<TBFOTO>("TBFOTOes"); } }
        [Association(@"TBGOSNAGRADIReferencesTBMAIN", typeof(TBGOSNAGRADI))]
        public XPCollection<TBGOSNAGRADI> TBGOSNAGRADIs { get { return GetCollection<TBGOSNAGRADI>("TBGOSNAGRADIs"); } }
        [Association(@"TBMESTORABReferencesTBMAIN", typeof(TBMESTORAB))]
        public XPCollection<TBMESTORAB> TBMESTORABs { get { return GetCollection<TBMESTORAB>("TBMESTORABs"); } }
        [Association(@"TBPOVISHKVALReferencesTBMAIN", typeof(TBPOVISHKVAL))]
        public XPCollection<TBPOVISHKVAL> TBPOVISHKVALs { get { return GetCollection<TBPOVISHKVAL>("TBPOVISHKVALs"); } }
        [Association(@"TBQARINDOSHReferencesTBMAIN", typeof(TBQARINDOSH))]
        public XPCollection<TBQARINDOSH> TBQARINDOSHes { get { return GetCollection<TBQARINDOSH>("TBQARINDOSHes"); } }
        [Association(@"TBUNIVERReferencesTBMAIN", typeof(TBUNIVER))]
        public XPCollection<TBUNIVER> TBUNIVERs { get { return GetCollection<TBUNIVER>("TBUNIVERs"); } }
    }

}
