//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Asbt.Data.Xpo
{

    public partial class TBPOVISHKVAL : XPLiteObject
    {
        int fID;
        [Key]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        TBMAIN fMAINID;
        [Size(50)]
        [Association(@"TBPOVISHKVALReferencesTBMAIN")]
        public TBMAIN MAINID
        {
            get { return fMAINID; }
            set { SetPropertyValue<TBMAIN>("MAINID", ref fMAINID, value); }
        }
        DateTime fDATE_PK;
        public DateTime DATE_PK
        {
            get { return fDATE_PK; }
            set { SetPropertyValue<DateTime>("DATE_PK", ref fDATE_PK, value); }
        }
        int fMESTO_PK;
        public int MESTO_PK
        {
            get { return fMESTO_PK; }
            set { SetPropertyValue<int>("MESTO_PK", ref fMESTO_PK, value); }
        }
        int fPOSLEDNIY_PK;
        public int POSLEDNIY_PK
        {
            get { return fPOSLEDNIY_PK; }
            set { SetPropertyValue<int>("POSLEDNIY_PK", ref fPOSLEDNIY_PK, value); }
        }
        int fNUM_SERTIFICAT;
        public int NUM_SERTIFICAT
        {
            get { return fNUM_SERTIFICAT; }
            set { SetPropertyValue<int>("NUM_SERTIFICAT", ref fNUM_SERTIFICAT, value); }
        }
        DateTime fEDITDATE;
        public DateTime EDITDATE
        {
            get { return fEDITDATE; }
            set { SetPropertyValue<DateTime>("EDITDATE", ref fEDITDATE, value); }
        }
        int fEDITUSER;
        public int EDITUSER
        {
            get { return fEDITUSER; }
            set { SetPropertyValue<int>("EDITUSER", ref fEDITUSER, value); }
        }
        int fSROK_PALN_PK;
        public int SROK_PALN_PK
        {
            get { return fSROK_PALN_PK; }
            set { SetPropertyValue<int>("SROK_PALN_PK", ref fSROK_PALN_PK, value); }
        }
    }

}
