//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Asbt.Data.Xpo
{

    public partial class TBUNIVER : XPLiteObject
    {
        int fPROFESIANAL_OBRAZ;
        public int PROFESIANAL_OBRAZ
        {
            get { return fPROFESIANAL_OBRAZ; }
            set { SetPropertyValue<int>("PROFESIANAL_OBRAZ", ref fPROFESIANAL_OBRAZ, value); }
        }
        string fSERIYA;
        [Size(5)]
        public string SERIYA
        {
            get { return fSERIYA; }
            set { SetPropertyValue<string>("SERIYA", ref fSERIYA, value); }
        }
        int fNUM;
        public int NUM
        {
            get { return fNUM; }
            set { SetPropertyValue<int>("NUM", ref fNUM, value); }
        }
        int fOB_TYPE;
        public int OB_TYPE
        {
            get { return fOB_TYPE; }
            set { SetPropertyValue<int>("OB_TYPE", ref fOB_TYPE, value); }
        }
        int fID;
        [Key]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        TBMAIN fMAINID;
        [Size(50)]
        [Association(@"TBUNIVERReferencesTBMAIN")]
        public TBMAIN MAINID
        {
            get { return fMAINID; }
            set { SetPropertyValue<TBMAIN>("MAINID", ref fMAINID, value); }
        }
        string fGOD_VIPUSKA;
        [Size(4)]
        public string GOD_VIPUSKA
        {
            get { return fGOD_VIPUSKA; }
            set { SetPropertyValue<string>("GOD_VIPUSKA", ref fGOD_VIPUSKA, value); }
        }
        int fOBRAZOVATELNIY_UCHERJ;
        public int OBRAZOVATELNIY_UCHERJ
        {
            get { return fOBRAZOVATELNIY_UCHERJ; }
            set { SetPropertyValue<int>("OBRAZOVATELNIY_UCHERJ", ref fOBRAZOVATELNIY_UCHERJ, value); }
        }
        string fSPECIALNOST_PODIPLOMU;
        [Size(400)]
        public string SPECIALNOST_PODIPLOMU
        {
            get { return fSPECIALNOST_PODIPLOMU; }
            set { SetPropertyValue<string>("SPECIALNOST_PODIPLOMU", ref fSPECIALNOST_PODIPLOMU, value); }
        }
        int fVID_OBUCHENIYA;
        public int VID_OBUCHENIYA
        {
            get { return fVID_OBUCHENIYA; }
            set { SetPropertyValue<int>("VID_OBUCHENIYA", ref fVID_OBUCHENIYA, value); }
        }
        DateTime fEDITDATE;
        public DateTime EDITDATE
        {
            get { return fEDITDATE; }
            set { SetPropertyValue<DateTime>("EDITDATE", ref fEDITDATE, value); }
        }
        int fEDITUSER;
        public int EDITUSER
        {
            get { return fEDITUSER; }
            set { SetPropertyValue<int>("EDITUSER", ref fEDITUSER, value); }
        }
    }

}
